Repository TrueEchoProject/TrueEcho_Main, pull requests merged in 2024-04, with the labels that each got.

#88 BE06-1/feat/post_retrieval -> refactor : refresh 토큰 email 저장
  src/main/java/te/trueEcho/domain/user/entity/User.java
  src/main/java/te/trueEcho/global/security/jwt/Repository/RefreshTokenRepository.java
  src/main/java/te/trueEcho/global/security/jwt/service/JwtService.java
Labels: 😎refactor

#89 [FEATURE] '회원정보 수정/조회 구현'
  build.gradle
  src/main/java/te/trueEcho/domain/friend/repository/FriendRepositoryImpl.java
  src/main/java/te/trueEcho/domain/notification/entity/Notification.java
  src/main/java/te/trueEcho/domain/post/entity/Pin.java
  src/main/java/te/trueEcho/domain/post/entity/Post.java
  src/main/java/te/trueEcho/domain/user/controller/UserAuthController.java
  src/main/java/te/trueEcho/domain/user/controller/UserController.java
  src/main/java/te/trueEcho/domain/user/converter/SignUpDtoToUserConverter.java
  src/main/java/te/trueEcho/domain/user/dto/EditUserRequest.java
  src/main/java/te/trueEcho/domain/user/dto/EditUserResponse.java
  src/main/java/te/trueEcho/domain/user/dto/SignUpUserDto.java
  src/main/java/te/trueEcho/domain/user/entity/NotiTimeStatus.java
  src/main/java/te/trueEcho/domain/user/entity/User.java
  src/main/java/te/trueEcho/domain/user/repository/UserRepository.java
  src/main/java/te/trueEcho/domain/user/repository/UserRepositoryImpl.java
  src/main/java/te/trueEcho/domain/user/service/UserAuthServiceImpl.java
  src/main/java/te/trueEcho/domain/user/service/UserService.java
  src/main/java/te/trueEcho/domain/vote/entity/Vote.java
  src/main/java/te/trueEcho/domain/vote/entity/VoteResult.java
  src/main/java/te/trueEcho/global/config/audit/JpaAuditConfig.java
  src/main/java/te/trueEcho/global/entity/CreatedDateAudit.java
  src/main/java/te/trueEcho/global/entity/FullAudit.java
  src/main/java/te/trueEcho/global/response/ResponseCode.java
  src/main/java/te/trueEcho/global/security/jwt/Repository/RefreshTokenRepository.java
  src/main/java/te/trueEcho/global/security/jwt/config/SecurityConfig.java
  src/main/java/te/trueEcho/global/security/jwt/controller/JwtController.java
  src/main/java/te/trueEcho/global/security/jwt/service/JwtService.java
  src/main/java/te/trueEcho/global/util/AuthUtil.java
Labels: 💥feature, 😒chore, 😎refactor

#93 BE06-1/feat/post_retrieval
  .gitignore
  build.gradle
  src/main/java/te/trueEcho/domain/friend/entity/Friend.java
  src/main/java/te/trueEcho/domain/friend/entity/FriendStatus.java
  src/main/java/te/trueEcho/domain/friend/repository/FriendRepositoryImpl.java
  src/main/java/te/trueEcho/domain/post/controller/PostController.java
  src/main/java/te/trueEcho/domain/post/converter/PostToDtoConverter.java
  src/main/java/te/trueEcho/domain/post/dto/CommentDto.java
  src/main/java/te/trueEcho/domain/post/dto/CommentListDto.java
  src/main/java/te/trueEcho/domain/post/dto/FeedType.java
  src/main/java/te/trueEcho/domain/post/dto/PostDto.java
  src/main/java/te/trueEcho/domain/post/dto/PostGetDto.java
  src/main/java/te/trueEcho/domain/post/dto/PostListDto.java
  src/main/java/te/trueEcho/domain/post/dto/WriterDto.java
  src/main/java/te/trueEcho/domain/post/repository/PostRepository.java
  src/main/java/te/trueEcho/domain/post/repository/PostRepositoryImpl.java
  src/main/java/te/trueEcho/domain/post/service/PostService.java
  src/main/java/te/trueEcho/domain/post/service/PostServiceImpl.java
  src/main/java/te/trueEcho/domain/user/controller/UserAuthController.java
  src/main/java/te/trueEcho/domain/user/converter/SignUpDtoToUserConverter.java
  src/main/java/te/trueEcho/domain/user/entity/User.java
  src/main/java/te/trueEcho/domain/user/repository/UserAuthRepository.java
  src/main/java/te/trueEcho/domain/user/repository/UserAuthRepositoryImpl.java
  src/main/java/te/trueEcho/domain/user/repository/UserRepository.java
  src/main/java/te/trueEcho/domain/user/service/EmailCodeService.java
  src/main/java/te/trueEcho/domain/user/service/UserAuthService.java
  src/main/java/te/trueEcho/domain/user/service/UserAuthServiceImpl.java
  src/main/java/te/trueEcho/domain/user/service/UserService.java
  src/main/java/te/trueEcho/global/entity/Audit.java
  src/main/java/te/trueEcho/global/response/ResponseCode.java
  src/main/java/te/trueEcho/global/security/jwt/JwtFilter.java
  src/main/java/te/trueEcho/global/security/jwt/config/SecurityConfig.java
  src/main/java/te/trueEcho/global/security/jwt/controller/JwtController.java
  src/main/java/te/trueEcho/global/security/jwt/service/CustomUserDetailsService.java
  src/main/java/te/trueEcho/global/security/jwt/service/JwtService.java
  src/main/java/te/trueEcho/global/util/AuthUtil.java
  src/main/resources/application.properties
Labels: 💥feature, 😒chore, ✔️document, 😎refactor, 👻test

#94 BE06-2/feat/post_retrieval
  src/main/java/te/trueEcho/domain/post/controller/PostController.java
  src/main/java/te/trueEcho/domain/post/controller/VoteController.java
  src/main/java/te/trueEcho/domain/post/converter/CommentToDtoConverter.java
  src/main/java/te/trueEcho/domain/post/converter/PostToDtoConverter.java
  src/main/java/te/trueEcho/domain/post/dto/CommentDto.java
  src/main/java/te/trueEcho/domain/post/dto/CommentListResponse.java
  src/main/java/te/trueEcho/domain/post/dto/CommentResponse.java
  src/main/java/te/trueEcho/domain/post/dto/FeedType.java
  src/main/java/te/trueEcho/domain/post/dto/PostListResponse.java
  src/main/java/te/trueEcho/domain/post/dto/PostRequest.java
  src/main/java/te/trueEcho/domain/post/dto/PostResponse.java
  src/main/java/te/trueEcho/domain/post/dto/WriterDto.java
  src/main/java/te/trueEcho/domain/post/entity/Comment.java
  src/main/java/te/trueEcho/domain/post/entity/Post.java
  src/main/java/te/trueEcho/domain/post/entity/PostStatus.java
  src/main/java/te/trueEcho/domain/post/entity/UnderComment.java
  src/main/java/te/trueEcho/domain/post/repository/PostRepository.java
  src/main/java/te/trueEcho/domain/post/repository/PostRepositoryImpl.java
  src/main/java/te/trueEcho/domain/post/repository/VoteRepository.java
  src/main/java/te/trueEcho/domain/post/repository/VoteRepositoryImpl.java
  src/main/java/te/trueEcho/domain/post/service/PostService.java
  src/main/java/te/trueEcho/domain/post/service/PostServiceImpl.java
  src/main/java/te/trueEcho/domain/post/service/VoteService.java
  src/main/java/te/trueEcho/domain/post/service/VoteServiceImpl.java
  src/main/java/te/trueEcho/domain/user/controller/UserAuthController.java
  src/main/java/te/trueEcho/domain/user/converter/SignUpDtoToUserConverter.java
  src/main/java/te/trueEcho/domain/user/dto/CheckCodeRequest.java
  src/main/java/te/trueEcho/domain/user/dto/EditUserDto.java
  src/main/java/te/trueEcho/domain/user/dto/EmailRequest.java
  src/main/java/te/trueEcho/domain/user/dto/LoginRequest.java
  src/main/java/te/trueEcho/domain/user/dto/RegisterRequest.java
  src/main/java/te/trueEcho/domain/user/repository/UserRepository.java
  src/main/java/te/trueEcho/domain/user/service/EmailCodeService.java
  src/main/java/te/trueEcho/domain/user/service/UserAuthService.java
  src/main/java/te/trueEcho/domain/user/service/UserAuthServiceImpl.java
  src/main/java/te/trueEcho/global/response/ResponseCode.java
  src/main/java/te/trueEcho/global/security/jwt/controller/JwtController.java
  src/main/java/te/trueEcho/global/security/jwt/service/JwtService.java
Labels: 💥feature, 😎refactor

#95 Be02 2/feat/about user
  build.gradle
  src/main/java/te/trueEcho/TrueEchoApplication.java
  src/main/java/te/trueEcho/domain/user/controller/BlockController.java
  src/main/java/te/trueEcho/domain/user/controller/UserAuthController.java
  src/main/java/te/trueEcho/domain/user/controller/UserController.java
  src/main/java/te/trueEcho/domain/user/dto/EditUserResponse.java
  src/main/java/te/trueEcho/domain/user/entity/User.java
  src/main/java/te/trueEcho/domain/user/repository/EmailMemoryRepository.java
  src/main/java/te/trueEcho/domain/user/repository/SuspendedUserRepository.java
  src/main/java/te/trueEcho/domain/user/repository/UserAuthRepositoryImpl.java
  src/main/java/te/trueEcho/domain/user/repository/UserRepository.java
  src/main/java/te/trueEcho/domain/user/service/UserService.java
  src/main/java/te/trueEcho/global/entity/Audit.java
  src/main/java/te/trueEcho/global/response/ResponseCode.java
  src/main/java/te/trueEcho/global/response/ResponseForm.java
  src/main/java/te/trueEcho/global/security/jwt/controller/JwtController.java
Labels: 😶‍🌫️bug, 💥feature, 😎refactor

#98 BE07-1/feat/vote
  src/main/java/te/trueEcho/domain/post/controller/VoteController.java
  src/main/java/te/trueEcho/domain/post/converter/CommentToDtoConverter.java
  src/main/java/te/trueEcho/domain/post/converter/PostToPhotoDtoConverter.java
  src/main/java/te/trueEcho/domain/post/dto/CommentResponse.java
  src/main/java/te/trueEcho/domain/post/dto/FeedType.java
  src/main/java/te/trueEcho/domain/post/entity/Comment.java
  src/main/java/te/trueEcho/domain/post/entity/UnderComment.java
  src/main/java/te/trueEcho/domain/post/repository/VoteRepository.java
  src/main/java/te/trueEcho/domain/post/repository/VoteRepositoryImpl.java
  src/main/java/te/trueEcho/domain/post/service/PostServiceImpl.java
  src/main/java/te/trueEcho/domain/post/service/VoteService.java
  src/main/java/te/trueEcho/domain/post/service/VoteServiceImpl.java
  src/main/java/te/trueEcho/domain/user/repository/EmailMemoryRepository.java
  src/main/java/te/trueEcho/domain/user/repository/UserRepository.java
  src/main/java/te/trueEcho/domain/user/service/UserService.java
  src/main/java/te/trueEcho/domain/vote/controller/VoteController.java
  src/main/java/te/trueEcho/domain/vote/converter/VoteToDtoConverter.java
  src/main/java/te/trueEcho/domain/vote/converter/VoteUserToDtoConverter.java
  src/main/java/te/trueEcho/domain/vote/dto/PhotoResponse.java
  src/main/java/te/trueEcho/domain/vote/dto/TargetUserResponse.java
  src/main/java/te/trueEcho/domain/vote/dto/VoteContentsResponse.java
  src/main/java/te/trueEcho/domain/vote/dto/VoteResponse.java
  src/main/java/te/trueEcho/domain/vote/dto/VoteResultRequest.java
  src/main/java/te/trueEcho/domain/vote/dto/VoteUsersResponse.java
  src/main/java/te/trueEcho/domain/vote/entity/VoteResult.java
  src/main/java/te/trueEcho/domain/vote/repository/VoteRepository.java
  src/main/java/te/trueEcho/domain/vote/repository/VoteRepositoryImpl.java
  src/main/java/te/trueEcho/domain/vote/repository/VoteType.java
  src/main/java/te/trueEcho/domain/vote/service/VoteService.java
  src/main/java/te/trueEcho/domain/vote/service/VoteServiceImpl.java
  src/main/java/te/trueEcho/global/response/ResponseCode.java
  src/main/java/te/trueEcho/global/security/jwt/controller/JwtController.java
  src/test/java/te/test/VoteUserToDtoConverterTest.java
Labels: 💥feature

#99 Be04-1/feat/friend_and_blocks
  build.gradle
  src/main/java/te/trueEcho/domain/friend/controller/FriendController.java
  src/main/java/te/trueEcho/domain/friend/dto/AddFriendRequest.java
  src/main/java/te/trueEcho/domain/friend/dto/ConfirmFriendResponse.java
  src/main/java/te/trueEcho/domain/friend/dto/FriendListResponse.java
  src/main/java/te/trueEcho/domain/friend/entity/Friend.java
  src/main/java/te/trueEcho/domain/friend/entity/FriendStatus.java
  src/main/java/te/trueEcho/domain/friend/repository/FriendRepository.java
  src/main/java/te/trueEcho/domain/friend/repository/FriendRepositoryImpl.java
  src/main/java/te/trueEcho/domain/friend/service/FriendService.java
  src/main/java/te/trueEcho/domain/post/controller/PostController.java
  src/main/java/te/trueEcho/domain/post/entity/Comment.java
  src/main/java/te/trueEcho/domain/user/controller/BlockController.java
  src/main/java/te/trueEcho/domain/user/dto/BlockListResponse.java
  src/main/java/te/trueEcho/domain/user/entity/Block.java
  src/main/java/te/trueEcho/domain/user/entity/User.java
  src/main/java/te/trueEcho/domain/user/repository/BlockRepository.java
  src/main/java/te/trueEcho/domain/user/service/BlockService.java
  src/main/java/te/trueEcho/global/response/ResponseCode.java
  src/test/java/te/trueEcho/domain/friend/controller/FriendControllerTest.java
Labels: 💥feature, 😒chore

#101 Be05-01/feat/photos
  build.gradle
  src/main/java/te/trueEcho/domain/friend/controller/FriendController.java
  src/main/java/te/trueEcho/domain/friend/entity/Friend.java
  src/main/java/te/trueEcho/domain/friend/repository/FriendRepositoryImpl.java
  src/main/java/te/trueEcho/domain/friend/service/FriendService.java
  src/main/java/te/trueEcho/domain/post/controller/PostController.java
  src/main/java/te/trueEcho/domain/post/converter/PostToDtoConverter.java
  src/main/java/te/trueEcho/domain/post/dto/AddPostRequest.java
  src/main/java/te/trueEcho/domain/post/dto/PostListResponse.java
  src/main/java/te/trueEcho/domain/post/dto/ReadPostRequest.java
  src/main/java/te/trueEcho/domain/post/dto/ReadPostResponse.java
  src/main/java/te/trueEcho/domain/post/entity/Post.java
  src/main/java/te/trueEcho/domain/post/entity/PostStatus.java
  src/main/java/te/trueEcho/domain/post/repository/PostRepository.java
  src/main/java/te/trueEcho/domain/post/repository/PostRepositoryImpl.java
  src/main/java/te/trueEcho/domain/post/service/PostService.java
  src/main/java/te/trueEcho/domain/post/service/PostServiceImpl.java
  src/main/java/te/trueEcho/domain/vote/repository/VoteRepository.java
  src/main/java/te/trueEcho/domain/vote/repository/VoteRepositoryImpl.java
  src/main/java/te/trueEcho/global/response/ResponseCode.java
  src/main/java/te/trueEcho/infra/azure/AzureUploader.java
  src/main/java/te/trueEcho/infra/azure/EnvFileLoader.java
  src/main/resources/application.properties
Labels: 💥feature, 😒chore, 😎refactor
