Repository TrueEchoProject/TrueEcho_Main, pull requests merged in 2024-06, with the labels that each got.

#132 BE-fix[스웨거 작업]
  src/main/java/te/trueEcho/domain/friend/controller/FriendController.java
  src/main/java/te/trueEcho/domain/notification/controller/NotificationController.java
  src/main/java/te/trueEcho/domain/post/controller/PostController.java
  src/main/java/te/trueEcho/domain/rank/controller/RankController.java
  src/main/java/te/trueEcho/domain/rank/dto/RankResponse.java
  src/main/java/te/trueEcho/domain/rank/dto/RankUserResponse.java
  src/main/java/te/trueEcho/domain/rank/service/RankServiceImpl.java
  src/main/java/te/trueEcho/domain/rank/service/ScheduledRankService.java
  src/main/java/te/trueEcho/domain/setting/controller/SettingController.java
  src/main/java/te/trueEcho/domain/setting/dto/calendar/MonthlyPostListResponse.java
  src/main/java/te/trueEcho/domain/setting/dto/calendar/MonthlyPostResponse.java
  src/main/java/te/trueEcho/domain/setting/dto/mypage/EditMyInfoRequest.java
  src/main/java/te/trueEcho/domain/setting/dto/mypage/MyInfoResponse.java
  src/main/java/te/trueEcho/domain/setting/dto/mypage/MyPageResponse.java
  src/main/java/te/trueEcho/domain/setting/dto/mypage/OtherPageResponse.java
  src/main/java/te/trueEcho/domain/setting/dto/notiset/CommunityNotiSet.java
  src/main/java/te/trueEcho/domain/setting/dto/notiset/NotificationSettingDto.java
  src/main/java/te/trueEcho/domain/setting/dto/notiset/PostNotiSet.java
  src/main/java/te/trueEcho/domain/setting/dto/pin/PinListResponse.java
  src/main/java/te/trueEcho/domain/setting/dto/pin/PinResponse.java
  src/main/java/te/trueEcho/domain/setting/dto/pin/PinsRequest.java
  src/main/java/te/trueEcho/domain/setting/dto/random/RandomNotifyTResponse.java
  src/main/java/te/trueEcho/domain/user/controller/BlockController.java
  src/main/java/te/trueEcho/domain/user/controller/UserAuthController.java
  src/main/java/te/trueEcho/domain/user/controller/UserController.java
  src/main/java/te/trueEcho/domain/user/dto/BlockListResponse.java
  src/main/java/te/trueEcho/domain/user/dto/CheckCodeRequest.java
  src/main/java/te/trueEcho/domain/user/dto/EditUserRequest.java
  src/main/java/te/trueEcho/domain/user/dto/EditUserResponse.java
  src/main/java/te/trueEcho/domain/user/dto/LoginRequest.java
  src/main/java/te/trueEcho/domain/user/dto/RegisterRequest.java
  src/main/java/te/trueEcho/domain/user/dto/UpdatePasswordRequest.java
  src/main/java/te/trueEcho/domain/user/dto/UserCheckRequest.java
  src/main/java/te/trueEcho/domain/vote/controller/VoteController.java
  src/main/java/te/trueEcho/domain/vote/dto/PhotoResponse.java
  src/main/java/te/trueEcho/domain/vote/dto/TargetUserResponse.java
  src/main/java/te/trueEcho/domain/vote/dto/VoteContentsResponse.java
  src/main/java/te/trueEcho/domain/vote/dto/VoteResponse.java
  src/main/java/te/trueEcho/domain/vote/dto/VoteResultRequest.java
  src/main/java/te/trueEcho/domain/vote/dto/VoteUsersResponse.java
  src/main/java/te/trueEcho/domain/vote/repository/VoteRepositoryImpl.java
  src/main/java/te/trueEcho/domain/vote/service/VoteServiceImpl.java
  src/main/java/te/trueEcho/global/config/SwaggerConfig.java
  src/main/java/te/trueEcho/global/security/jwt/config/SecurityConfig.java
  src/main/java/te/trueEcho/global/security/jwt/controller/JwtController.java
  src/main/java/te/trueEcho/global/security/jwt/dto/TokenDto.java
  src/main/java/te/trueEcho/infra/firebase/controller/FCMController.java
  src/main/java/te/trueEcho/infra/firebase/dto/FCMTokenResponse.java
  src/main/java/te/trueEcho/infra/kakao/dto/KakaoResponse.java
Labels: 😒chore

#143 BE/bug/likes
  src/main/java/te/trueEcho/domain/post/converter/PostToDto.java
  src/main/java/te/trueEcho/domain/rank/entity/Rank.java
  src/main/java/te/trueEcho/infra/firebase/config/FirebaseConfig.java
Labels: 😶‍🌫️bug

#144 BE/bug/vote_content
  build.gradle
  src/main/java/te/trueEcho/domain/notification/service/NotificationServiceImpl.java
  src/main/java/te/trueEcho/domain/post/service/PostServiceImpl.java
  src/main/java/te/trueEcho/domain/rank/entity/Rank.java
  src/main/java/te/trueEcho/domain/setting/dto/pin/PinsRequest.java
  src/main/java/te/trueEcho/domain/setting/entity/NotificationSetting.java
  src/main/java/te/trueEcho/domain/setting/service/SettingServiceImpl.java
  src/main/java/te/trueEcho/domain/user/entity/User.java
  src/main/java/te/trueEcho/domain/vote/service/VoteServiceImpl.java
  src/main/java/te/trueEcho/infra/firebase/config/FirebaseConfig.java
  src/main/java/te/trueEcho/infra/firebase/service/FCMService.java
  src/main/resources/application.properties
Labels: 😶‍🌫️bug

#145 BE/feat/post/response
  src/main/java/te/trueEcho/domain/post/controller/PostController.java
  src/main/java/te/trueEcho/domain/post/converter/PostToDto.java
  src/main/java/te/trueEcho/domain/post/dto/ReadPostResponse.java
  src/main/java/te/trueEcho/domain/post/repository/PostRepositoryImpl.java
  src/main/java/te/trueEcho/domain/post/service/PostService.java
  src/main/java/te/trueEcho/domain/post/service/PostServiceImpl.java
  src/main/java/te/trueEcho/domain/setting/controller/SettingController.java
  src/main/java/te/trueEcho/domain/user/controller/UserAuthController.java
  src/main/java/te/trueEcho/domain/user/dto/UpdatePasswordRequest.java
  src/main/java/te/trueEcho/domain/user/entity/User.java
  src/main/java/te/trueEcho/global/response/ExceptionResponse.java
  src/main/java/te/trueEcho/global/response/ResponseInterface.java
Labels: 😶‍🌫️bug, 😉enhancement, 💥feature, 😎refactor

#149 feat : 알림, 랭킹, 친구 멀티 이슈 처리
  src/main/java/te/trueEcho/domain/friend/controller/FriendController.java
  src/main/java/te/trueEcho/domain/friend/repository/FriendRepositoryImpl.java
  src/main/java/te/trueEcho/domain/friend/service/FriendService.java
  src/main/java/te/trueEcho/domain/notification/service/NotificationServiceImpl.java
  src/main/java/te/trueEcho/domain/post/entity/Comment.java
  src/main/java/te/trueEcho/domain/post/entity/Like.java
  src/main/java/te/trueEcho/domain/rank/entity/Rank.java
  src/main/java/te/trueEcho/domain/rank/service/ScheduledRankService.java
  src/main/java/te/trueEcho/domain/vote/entity/VoteResult.java
  src/main/java/te/trueEcho/global/response/ResponseCode.java
Labels: 😶‍🌫️bug, 💥feature, 😎refactor

#147 feat : 이미지 블러처리 기능 (PostedIn24H)
  src/main/java/te/trueEcho/domain/post/controller/PostController.java
  src/main/java/te/trueEcho/domain/post/converter/PostToDto.java
  src/main/java/te/trueEcho/domain/post/dto/PostListResponse.java
  src/main/java/te/trueEcho/domain/post/dto/PostedIn24H.java
  src/main/java/te/trueEcho/domain/post/dto/ReadPostRequest.java
  src/main/java/te/trueEcho/domain/post/dto/ReadPostResponse.java
  src/main/java/te/trueEcho/domain/post/dto/SinglePostRequest.java
  src/main/java/te/trueEcho/domain/post/repository/PostRepository.java
  src/main/java/te/trueEcho/domain/post/repository/PostRepositoryImpl.java
  src/main/java/te/trueEcho/domain/post/service/PostService.java
  src/main/java/te/trueEcho/domain/post/service/PostServiceImpl.java
  src/main/java/te/trueEcho/domain/vote/service/VoteServiceImpl.java
Labels: 💥feature, 😎refactor
